openapi: 3.0.0
info:
  title: Library Management API
  description: API for managing a library API
  version: 1.0.0
servers:
  - url: http://library-management.com
paths:
  /books:
    get:
      tags:
        - Book
      summary: Get book by bookName and releaseDate
      operationId: getBook
      parameters:
        - name: bookName
          in: query
          required: true
          schema:
            type: string
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: A book by bookName and releaseDate
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '404':
          description: No book found for the given parameters
    put:
      tags:
        - Book
      summary: Update or create a book
      operationId: updateOrCreateBook
      requestBody:
        description: Book to be updated or created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Book updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '201':
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Invalid input
  /books/{bookId}:
    delete:
      tags:
        - Book
      summary: Delete a book by ID
      operationId: deleteBook
      parameters:
        - name: bookId
          in: path
          required: true
          description: ID of the book to delete
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: book deleted successfully, no content returned
        '400':
          description: bookId not found
  /authors:
    get:
      tags:
        - Author
      summary: Get Author by name
      operationId: getAuthor
      parameters:
        - name: authorName
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A book by authorName
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
        '404':
          description: No author found for the given parameters
    put:
      tags:
        - Author
      summary: Update a Author by ID
      operationId: updateOrCreateAuthor
      requestBody:
        description: Author object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '200':
          description: Author updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '201':
          description: Author created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '400':
          description: Invalid input
  /authors/{authorId}:
    delete:
      tags:
        - Author
      summary: Delete a Author by ID
      operationId: deleteAuthor
      parameters:
        - name: authorId
          in: path
          required: true
          description: ID of the Author to delete
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Author deleted successfully, no content returned
        '400':
          description: authorId not found
components:
  schemas:
    Book:
      type: object
      properties:
        bookName:
          type: string
        bookId:
          type: integer
        pageNumbers:
          type: integer
        Author: 
          type: object
          items:
            $ref: '#/components/schemas/Author'
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
            type: string
            format: date-time        
    Author:
      type: object
      properties:
            authorId:
              type: integer
            authorName:
              type: string
            sex:
              type: string
              enum: 
                - M
                - F
